CREATE TABLE IF NOT EXISTS orders 
(
	"id" SERIAL Primary Key, 
	user_id INT NOT NULL, 
	"status" VARCHAR(8) NOT NULL DEFAULT('active'),
	CONSTRAINT order_user_id FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
);